List<String> questionsData=[
  "She ate an apple",
  "He drank the water",
  "They read a book",
  "We watched a movie",
  "You wrote a letter",
  "I bought a new car",
  "She listened to the music",
  "He played the guitar",
  "They cooked dinner",
  "We visited the museum",
  "She ate a juicy apple",
  "He drank the cold water",
  "They read an interesting book",
  "We watched a thrilling movie",
  "You wrote a long letter",
  "I bought a shiny new car",
  "She listened to the soothing music",
  "He played the melodious guitar",
  "They cooked a delicious dinner",
  "We visited the historic museum",
  "She ate an apple with a fork",
  "He drank the water from a glass",
  "They read a book on the beach",
  "We watched a movie in the theater",
  "You wrote a letter to your friend",
  "I bought a new car from the dealership",
  "She listened to music with her headphones",
  "He played the guitar for his friends",
  "They cooked dinner with fresh ingredients",
  "We visited the museum for an hour",
  "She ate the apple despite her allergies",
  "He drank the water after his workout",
  "They read a book about history",
  "We watched a movie with subtitles",
  "You wrote a letter for your boss",
  "I bought a new car with a loan",
  "She listened to music on her phone",
  "He played the guitar during the concert",
  "They cooked dinner for their family",
  "We visited the museum with a guide",
  "She ate that juicy apple",
  "He drank the cold water from this glass",
  "They read an interesting book about those events",
  "We watched that thrilling movie last night",
  "You wrote this long letter to your pen pal",
  "I bought that shiny new car last week",
  "She listened to that soothing music from her playlist",
  "He played the melodious guitar on that stage",
  "They cooked that delicious dinner for their guests",
  "We visited that historic museum in the city",
];